// UserRole const
export const UserRole = {
    ADMIN: 'ADMIN',
    VENDOR: 'VENDOR',
    PLATFORM: 'PLATFORM',
};

export const GET_VENDORS_SUCCESS = "GET_VENDORS_SUCCESS";
export const GET_VENDORS_FAILURE = "GET_VENDORS_FAILURE";
export const POST_VENDOR_SUCCESS = "POST_VENDOR_SUCCESS"
export const POST_VENDOR_FAILURE = "POST_VENDOR_FAILURE";
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS"
export const DELETE_VENDOR_FAILURE = "DELETE_VENDOR_FAILURE"

export const GET_USER_PROFILES_SUCCESS = "GET_USER_PROFILES_SUCCESS"
export const GET_USER_PROFILES_FAILURE = "GET_USER_PROFILES_FAILURE"
export const DELETE_USER_PROFILE_SUCCESS = "DELETE_USER_PROFILE_SUCCESS"
export const DELETE_USER_PROFILE_FAILURE = "DELETE_USER_PROFILE_FAILURE"

export const GET_PLATFORMS_SUCCESS = "GET_PLATFORMS_SUCCESS";
export const GET_PLATFORMS_FAILURE = "GET_PLATFORMS_FAILURE";
export const POST_PLATFORM_SUCCESS = "POST_PLATFORM_SUCCESS"
export const POST_PLATFORM_FAILURE = "POST_PLATFORM_FAILURE";
export const DELETE_PLATFORM_SUCCESS = "DELETE_PLATFORM_SUCCESS"
export const DELETE_PLATFORM_FAILURE = "DELETE_PLATFORM_FAILURE"
